<# Sign an existing build with a publisher-owned Windows code-signing certificate. #>
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$File,
    [Parameter(Mandatory=$true)][string]$CertificateThumbprint,
    [Parameter(Mandatory=$true)][string]$SignToolPath,
    [Parameter(Mandatory=$true)][string]$TimestampUrl
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
if ($CertificateThumbprint -notmatch '^[0-9a-fA-F]{40}$') { throw 'A publisher certificate thumbprint is required.' }
$timestampUri = [Uri]$TimestampUrl
if ($timestampUri.Scheme -ne 'https' -or $timestampUri.UserInfo -or $timestampUri.Fragment) { throw 'Use a trusted HTTPS RFC3161 timestamp endpoint supplied by your CA.' }
$targetFile = (Resolve-Path -LiteralPath $File).Path
$signTool = (Resolve-Path -LiteralPath $SignToolPath).Path
if ([IO.Path]::GetExtension($targetFile) -ne '.exe') { throw 'This signing step accepts EXE files only.' }
& $signTool sign /sha1 $CertificateThumbprint /s My /fd SHA256 /tr $TimestampUrl /td SHA256 $targetFile
if ($LASTEXITCODE -ne 0) { throw 'Code signing failed. No certificate or key is generated by this script.' }
$signature = Get-AuthenticodeSignature -LiteralPath $targetFile
if ($signature.Status -ne 'Valid' -or $signature.SignerCertificate.Thumbprint -ne $CertificateThumbprint -or -not $signature.TimeStamperCertificate) {
    throw 'Signed artifact failed publisher/timestamp validation.'
}
Write-Host "Verified publisher signature and timestamp: $targetFile"
